// Bachelor në "Inxhinieri Matematike dhe Informatike"
// Bachelor në "Biologji"
// Bachelor në "Bioteknologji"
// Bachelor në "Fizikë"
// Bachelor në "Informatikë"
// Bachelor në "Kimi dhe Teknologji Ushqimore"
// Bachelor në "Kimi Industriale e Mjedisore"
// Bachelor në "Kimi"
// Bachelor në "Matematikë"
// Bachelor në "Teknologji Informacioni dhe komunikimi"
// Master i Shkencave në "Biologji Mjedisore"
// Master i Shkencave në "Biologji Molekulare"
// Master i Shkencave në "Biologji", me profil "Mësues biologjie për arsimin e mesëm dhe të lartë"
// Master i Shkencave në "Bioteknologji Molekulare dhe Industriale"
// Master i Shkencave në "Fizikë"
// Master i Shkencave në "Fizikë", me profil "Mësues Fizike për arsimin e mesëm dhe të lartë"
// Master i Shkencave në "Informatikë"
// Master i Shkencave në "Informatikë", me profil "Mësues Informatike për arsimin e mesëm dhe të lartë"
// Master i Shkencave në "Inxhinieri Matematike dhe Informatike"
// Master i Shkencave në "Inxhinieria e Proceseve Kimike"
// Master i Shkencave në "Kimi Industriale dhe Mjedisore"
// Master i Shkencave në "Kimi"
// Master i Shkencave në "Kimi", me profil "Mësues Kimie për arsimin e mesëm dhe të lartë"
// Master i Shkencave në "Matematikë"
// Master i Shkencave në "Matematikë", me profil "Mësues Matematike për arsimin e mesëm dhe të lartë"
// Master i Shkencave në "Shkencat dhe Teknologjite Ushqimore"
// Master i Shkencave ne "Teknologji Informacioni"
// Master Profesional në "Bioteknologji Mjedisore"
// Master Profesional në "Informatikë Biznesi"
// Master Profesional në "Inxhinieri Matematike dhe Informatike"
// Master Profesional ne "Teknologji Informacioni"
